### ISSUE TITLE
[Interesting hunter meele attack bug] - Creature Related - Evade - Hit 

### ISSUE THREAD

**Issue by Wexez** [Arkania/ArkCORE-NG#126] opened 2016-04-10 13:09 UTC
Hi. I noticed a very strange bug related to specific heights/places/grounds/LoS related I think. It happens when you are at special grounds with special LoS. Eg in Mulgore at the birds (video linked below)
You hit a mob, you run away, you get out of combat, it returns with evade. You try to meele hit it, but it doesn't say evade, nor hit and it doesn't reset the state. 
THIS RESULTS in you not being able to meele hit until you relog. Very huge bug that should be looked into.

How to produce:
https://gyazo.com/9394255ec3e9f2548b5a9524498f3da2 (GIF)
Result/Bugged meele state:
https://gyazo.com/053c5515652151cc270c9e86e8fc73c6

Perhaps related to creature.cpp or player.cpp or unit.cpp attack function?

**Comment by gpn39f** [comment] 2016-04-10 23:57
i'm searching this last months..
but my skill is not high enough.. we need help for this..
one function i found is in map.cpp >> Map::isInLineOfSight().. read note to los2 (you can reproduce this by standing up on a GameObject.. you are not able to hit..)
maybe one of the parameter PositionZ related are wrong and give failure on different places..

**Comment by Wexez** [comment] 2016-04-11 06:44
Yeah kinda tough issue. I will dig into it and see if I can find more information

**Comment by gpn39f** [comment] 2016-04-11 17:47
super.. :-)

**Comment by UtilExe** [comment] 2016-04-14 17:59
I suspect it being a bit different of an issue.
Eg https://github.com/TrinityCore/TrinityCore/issues/13595
https://www.youtube.com/watch?v=KDNAECfx4rc&feature=youtu.be
The issue is different, but the logic is the same. It's just not resetting timer on ranged instead. That was fixed/temped by https://github.com/TrinityCore/TrinityCore/pull/14889/commits/20c8f5829ea8135bf7858894b419ea4d523ca2a7
Again, in this case it's meele attack handling instead. Might need a rework in that case. 
@gpn39f

**Comment by gpn39f** [comment] 2016-04-14 18:29
mhh i think you are searching in wrong direction..

go into map.cpp line 2424
remove my remark for line los2
now you will receive youre failure on many more places..

try:
move upto a gameobject and try to shoot: you will receive a message(similar): "the target is not in front of you", or "you can't do that".. and the aggro disappear, the evade mode is started.. 

and it seems, all failure has to do with position_Z ????
(and not a timer as you think ????)
but i could not find more..
please verify youre Theorie after remove my remark in line 2424
maybe there are 2 similar failure??

ups.. you are using god-mode and other extras..
pls try to use only gm command like .modify hp 99999 or .modify Speed 5

**Comment by UtilExe** [comment] 2016-04-14 19:13
@gpn39f 
Ahhh, I think we're looking/talking about two different things then. In my case, from my tests and what I meant is that this meele thing will bug ONLY if you hit the mob while it's evading.
So lets have an example:
Player A goes to attack creature B,
Player A runs away from creature B, 
Creature B runs after, but is too far so it goes back (evades), 
Player A (MEELE HITS) creature B while it's evading back.
Player A will now have the meele attack bug.

**Comment by gpn39f** [comment] 2016-04-19 06:45
please close this issue if you think it's done.. :-)

**Closed as completed** 2016-05-06 00:25 UTC
